[build]
  command = "npm install"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = ["views/**", "partials/**"]

[functions.server]
  external_node_modules = ["express", "ejs", "serverless-http", "@supabase/supabase-js"]
