[build]
  command = "npm install"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = ["views/**", "partials/**", "storage.cjs", "users.json", "recipes.json"]

[functions.server]
  external_node_modules = ["express", "ejs", "serverless-http"]
